### ISSUE TITLE
Setting string value for `on_map` fails dummy mapping generation

### ISSUE THREAD

**Issue by tgw314** [Shougo/dpp-ext-lazy#2]
# Problems summary
Setting string value for `on_map` fails dummy mapping generation.

## Expected
Dummy mapping generation does not fail even when a string value is set for the `on_map`.

## Environment Information

- dpp-ext-lazy version (SHA1): 20aff57790fc123f8916e56721c86a2ebfbfa4c1

- dpp.vim version (SHA1): https://github.com/Shougo/dpp.vim/commit/b0542d39cda9d387cb3088029d7353fd09069e70

- denops.vim version (SHA1): https://github.com/vim-denops/denops.vim/commit/ea7370bf5d323e83ee13ccba35f56e06db5753e1

- deno version(`deno -V` output): deno 1.37.2

- OS: Arch Linux

- neovim/Vim `:version` output: NVIM v0.10.0-dev-1388+g7a6e27958a

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
let $DPP_DIR = stdpath("data") . '/dpp'

execute 'set runtimepath+=' . $DPP_DIR . '/repos/github.com/Shougo/dpp.vim'
execute 'set runtimepath+=' . $DPP_DIR . '/repos/github.com/Shougo/dpp-ext-lazy'
execute 'set runtimepath+=' . $DPP_DIR . '/repos/github.com/vim-denops/denops.vim'

autocmd User DenopsReady call dpp#make_state($DPP_DIR, stdpath("config") . '/config.ts')
```
```typescript
import {
  BaseConfig,
  ConfigReturn,
  ContextBuilder,
  Dpp,
  Plugin,
} from "https://deno.land/x/dpp_vim@v0.0.7/types.ts";
import { Denops, fn } from "https://deno.land/x/dpp_vim@v0.0.7/deps.ts";

export class Config extends BaseConfig {
  override async config(args: {
    denops: Denops;
    contextBuilder: ContextBuilder;
    basePath: string;
    dpp: Dpp;
  }): Promise<ConfigReturn> {
    const [context, options] = await args.contextBuilder.get(args.denops);

    await args.dpp.extAction(
      args.denops,
      context,
      options,
      "lazy",
      "makeState",
      {
        plugins: [{
          name: "dpp.vim",
          path: await fn.expand(
            args.denops,
            "$DPP_DIR/repos/github.com/Shougo/dpp.vim",
          ),
          on_map: "j",
        }],
      },
    );

    return {
      plugins: [] as Plugin[],
    };
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Place these files in `$XDG_CONFIG_HOME/nvim-minimal/`
2. Run `NVIM_APPNAME=nvim-minimal nvim`

## Upload the log messages by `:redir` and `:message` (if errored)
```
[denops] Failed to handle message 2,invoke,dispatch,dpp,makeState,/home/{username}/.local/share/nvim-minimal/dpp,/home/{username}/.config/nvim-minimal/config.ts,nvim 0,function dpp#ext#lazy#_generate_dummy_mappings, line 7: Vim(let):E928: String required
```

**Comment by Shougo** [comment]
Fixed.
